### PR TITLE
Decrypt secrets

### PR DESCRIPTION
**Pull request by mcameron**

### CODE REVIEW

**Comment by geriBatai** [comment]
No. You are reusing terraform's tfvars for a completely different purpose with lots of assumptions about client's environment. Your change works fine in our corner case, but breaks badly in general. 

1. terragrunt apply-all can fail really badly when two modules are applied in parallel.
2. You hardcode special knowledge on a "special" file `/tmp/terragruntsecrets.tfvars` into the code. If people don't know where exactly to insert it, their code will behave in weird ways.
3. My terraform cannot have myvar = "ENCRYPTION_ENABLED" anymore.
4. You enforce kms usage on clients whether they want it or not. For example, terragrunt fails if I'm not using AWS at all, and it requires me to have AWS variables set.

I understand the appeal of doing decryption behind the scenes, but if that's the case, first it must become a first-class feature for terraform itself. If you still want to do this, we should at least:

1. Introduce new file types. Like .tfvars.enc or .tfenc
2. Determine how variable priorities work, as an example, what happens when I have password in both encrypted and unencrypted forms
3. Make this optional. Via cmdline arg or config file value

Otherwise I can't see how this can be merged to base.

**Comment by mcameron** [comment]
Ok so a few points.  Chief among which is that this is not a request to merge into "base".  

This is to merge into our already special cased, already broken version of terragrunt (you can't apply the same state as saved by a separate plan for example).   

Yes it would be better if terraform managed secrets properly.  You can see my thoughts on the matter here: https://github.com/hashicorp/terraform/issues/15434. 

Yes variables that begin with ENC can break a build.  Happy to make it ENC[var], however I judged that this is a design choice which is superior to most other options. 

The fact is that what we're trying to fix is plaintext secrets in bitesize modular.  This would enable that for us.

**Comment by geriBatai** [comment]
I'm not sure what you mean by "you can't apply the same state as saved by a separate plan for example", but if you think there's a bug we've introduced, you should raise it and we need to fix it, not deviate from the base even more. Please raise an issue, thanks.

**Comment by mcameron** [comment]
This PR is here to review the code and should assist in the review of https://github.com/pearsontechnology/bitesize-environments/pull/8, which is the actual PR that needs to be merged for me to close this story. 

It should not be merged into interpolation branch - which has a chance of being merged upstream.

**Pull request closed without merging**
